config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  namespace :students do
    resources :sections, only: %i[index new create] do
      collection do
        get 'download'
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(_auth_object = nil)
    column_names + _ransackers.keys
  end

  def self.ransackable_associations(_auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s } + _ransackers.keys
  end
end

app/models/classroom.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: classrooms
#
#  id          :bigint           not null, primary key
#  room_number :string           not null
#  building    :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Classroom < ApplicationRecord
  has_many :sections, dependent: :destroy

  validates :room_number, :building, presence: true
  validates :room_number, uniqueness: { scope: :building }
end

app/models/concerns/acts_as_full_name.rb
# frozen_string_literal: true

module ActsAsFullName
  extend ActiveSupport::Concern

  included do
    def full_name
      [first_name, last_name].compact.compact_blank.join(' ')
    end
  end
end

app/models/concerns/acts_as_reference_number.rb
# frozen_string_literal: true

module ActsAsReferenceNumber
  extend ActiveSupport::Concern

  included do
    before_validation(on: :create) do
      self.reference_number ||= SecureRandom.uuid
    end

    validates :reference_number, presence: true
  end
end

app/models/section.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sections
#
#  id                 :bigint           not null, primary key
#  title              :string           not null
#  teacher_subject_id :bigint           not null
#  classroom_id       :bigint           not null
#  weekdays           :integer          default([]), not null, is an Array
#  start_at           :time             not null
#  end_at             :time             not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Section < ApplicationRecord
  belongs_to :teacher_subject
  belongs_to :classroom
  has_one :teacher, through: :teacher_subject

  has_many :student_sections, dependent: :destroy
  has_many :students, through: :student_sections

  validates :title, :weekdays, :start_at, :end_at, presence: true
end

app/models/student.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: students
#
#  id               :bigint           not null, primary key
#  first_name       :text             not null
#  last_name        :text             not null
#  reference_number :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Student < ApplicationRecord
  include ActsAsFullName
  include ActsAsReferenceNumber

  has_many :student_sections, dependent: :destroy
  has_many :sections, through: :student_sections

  validates :first_name, :last_name, presence: true
end

app/models/student_section.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: student_sections
#
#  id         :bigint           not null, primary key
#  section_id :bigint           not null
#  student_id :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class StudentSection < ApplicationRecord
  belongs_to :section
  belongs_to :student

  validates :section, uniqueness: { scope: :student }
end

app/models/subject.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: subjects
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Subject < ApplicationRecord
  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects

  accepts_nested_attributes_for :teacher_subjects, allow_destroy: true

  validates :title, presence: true
end

app/models/teacher.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teachers
#
#  id               :bigint           not null, primary key
#  first_name       :string           not null
#  last_name        :string           not null
#  reference_number :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Teacher < ApplicationRecord
  include ActsAsFullName
  include ActsAsReferenceNumber

  has_many :teacher_subjects, dependent: :destroy
  has_many :subjects, through: :teacher_subjects
  has_many :sections, through: :teacher_subjects

  accepts_nested_attributes_for :teacher_subjects, allow_destroy: true

  validates :first_name, :last_name, presence: true
end

app/models/teacher_subject.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teacher_subjects
#
#  id         :bigint           not null, primary key
#  teacher_id :bigint           not null
#  subject_id :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TeacherSubject < ApplicationRecord
  belongs_to :teacher
  belongs_to :subject
  has_many :sections, dependent: :destroy

  validates :teacher, uniqueness: { scope: :subject }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] if params[:locale]
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/students/base_controller.rb
# frozen_string_literal: true

module Students
  class BaseController < ::ApplicationController
    before_action :current_student
    layout 'student'

    def current_student
      @current_student ||= Student.last || Student.create!(first_name: 'Test first', last_name: 'Test last')
    end
  end
end

app/controllers/students/sections_controller.rb
# frozen_string_literal: true

module Students
  class SectionsController < BaseController
    def index
      @sections = current_student.sections.all
    end

    def download
      respond_to do |format|
        format.pdf do
          render pdf: 'sections',
                 encoding: 'utf8'
        end
      end
    end

    def new
      @sections = Section.order(start_at: :asc).all
    end

    def create
      @section_form = Students::SectionForm.new(current_student.student_sections.new, section_params)
      if @section_form.save
        flash[:success] = 'Sucessfulyy joined section'
        redirect_to students_sections_path
      else
        flash[:error] = @section_form.errors.full_messages.join(', ')
        redirect_to new_students_section_path
      end
    end

    def destroy
      section = current_student.student_sections.find(params[:id])
      section.destroy
      redirect_to student_sections_path, notice: 'Successfully left section'
    end

    private

    def section_params
      params.require(:student_section).permit(:section_id)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/section_helper.rb
# frozen_string_literal: true

module SectionHelper
  def weekdays_string(weekdays)
    weekdays.map { |weekday| I18n.t("section.weekday_#{weekday}") }.join(', ')
  end

  def grouped_sections(sections)
    sections.group_by do |section|
      section.start_at.strftime('%H')
    end
  end
end

app/views/home/index.html.erb
<div class="test-container">
  <h2>School home</h2>

  <ul>
    <li><%= link_to 'I am teacher', admin_root_path %></li>
    <li><%= link_to 'I am student', students_sections_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>School home</title>
    <meta name="title" content="School home" />
    <meta charset="utf-8" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>Student zone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "student" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'shared/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert type">
    <%= message %>
  </div>
<% end %>

app/views/students/sections/download.pdf.erb
<h1>My Sections</h1>

app/views/students/sections/index.html.erb
<h1>My Sections</h1>

<li><%= link_to 'Join section', new_students_section_path %></li>

<% if @sections.present? %>
  <table>
    <thead>
      <tr>
        <th>Time</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
        <th>Sun</th>
      </tr>
    </thead>

    <tbody>
      <% grouped_sections(@sections).each do |time_slot, sections| %>
        <tr>
          <td><%= "#{time_slot}:00" %></td>
          <% (0..6).each do |weekday| %>
            <td>
              <%= sections.select { |i| weekday.in?(i.weekdays) }.map {|i| i.title }.join("\n") %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <li><%= link_to 'Download', download_students_sections_path, format: :pdf %></li>
<% else %>
  <h3>You are not in the any section</h3>
<% end %>

app/views/students/sections/new.html.erb
<% if @sections.present? %>
  <table>
    <thead>
      <tr>
        <th>Section</th>
        <th>Teacher</th>
        <th>Class location</th>
        <th>Week days</th>
        <th>Time</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @sections.each do |section| %>
        <tr>
          <td><%= section.title %></td>
          <td><%= section.teacher.full_name %></td>
          <td><%= "Building: #{section.classroom.building}; Room: ##{section.classroom.room_number}" %></td>
          <td><%= weekdays_string(section.weekdays) %></td>
          <td><%= "Form #{section.start_at.strftime('%H:%M')} to #{section.end_at.strftime('%H:%M')}" %></td>
          <td><%= button_to "Join", students_sections_path, method: "post", params: { student_section: { section_id: section.id } }  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>There is no sections to join</h3>
<% end %>